# fly.toml app configuration file generated for fitzyo on 2026-09-02T17:20:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fitzyo'
primary_region = 'dfw'
kill_signal = 'SIGTERM'

[build]
[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'fitzyo.com'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  
[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
