defmodule Fitzyo.NodeStep.Transformers.GenerateNodeDefinition do
  @moduledoc """
  Transformer that generates `node_definition/0` from the `node do ... end` DSL block.
  Runs before RegisterInNodeRegistry so the function is available when __register__/0 calls it.
  """
  use Spark.Dsl.Transformer

  alias Spark.Dsl.Transformer

  def before?(_), do: false
  def after?(_), do: false

  def transform(dsl_state) do
    kind = Transformer.get_option(dsl_state, [:node_def], :kind)
    label = Transformer.get_option(dsl_state, [:node_def], :label)
    category = Transformer.get_option(dsl_state, [:node_def], :category)
    color = Transformer.get_option(dsl_state, [:node_def], :color, :blue)
    icon = Transformer.get_option(dsl_state, [:node_def], :icon, "⬜")
    description = Transformer.get_option(dsl_state, [:node_def], :description, "")

    all_entities = Transformer.get_entities(dsl_state, [:node_def])
    config_options = Transformer.get_entities(dsl_state, [:node, :config])

    inputs = Enum.filter(all_entities, &is_struct(&1, Fitzyo.NodeStep.Input))
    outputs = Enum.filter(all_entities, &is_struct(&1, Fitzyo.NodeStep.Output))

    node_def = %Fitzyo.NodeStep.NodeDefinition{
      kind: kind,
      label: label,
      category: category,
      color: color,
      icon: icon,
      description: description,
      inputs: inputs,
      outputs: outputs,
      options: config_options
    }

    escaped = Macro.escape(node_def)

    code =
      quote do
        @doc "Returns the compile-time node definition for this step. Generated by Fitzyo.NodeStep DSL."
        def node_definition, do: unquote(escaped)
      end

    {:ok, Transformer.eval(dsl_state, [], code)}
  end
end
