create table MEN_RETAIL_PASSPORT (
  id bigint generated by default as identity primary key,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  measurement_date DATE,
  shirt_neck DECIMAL(4, 2),
  shirt_chest DECIMAL(4, 2),
  shirt_waist DECIMAL(4, 2),
  shirt_sleeve_length DECIMAL(4, 2),
  shirt_length DECIMAL(4, 2),
  pant_waist DECIMAL(4, 2),
  pant_hips DECIMAL(4, 2),
  pant_inseam DECIMAL(4, 2),
  pant_outseam DECIMAL(4, 2),
  belt_waist_size DECIMAL(4, 2),
  belt_length DECIMAL(4, 2),
  shoe_foot_length DECIMAL(4, 2),
  shoe_foot_width DECIMAL(4, 2),
  shoe_arch_length DECIMAL(4, 2),
  glove_hand_circumference DECIMAL(4, 2),
  glove_hand_length DECIMAL(4, 2)
  
);