defmodule Fitzyo.Repo.Migrations.Slice1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflow_nodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :node_kind, :text, null: false
      add :label, :text, null: false
      add :position_x, :float, default: 0.0
      add :position_y, :float, default: 0.0
      add :data, :map, default: %{}
      add :status, :text, default: "idle"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workflow_id,
          references(:workflows,
            column: :id,
            name: "workflow_nodes_workflow_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:workflow_executions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :context_snapshot, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workflow_id,
          references(:workflows,
            column: :id,
            name: "workflow_executions_workflow_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:workflow_executions, "workflow_executions_workflow_id_fkey")

    drop table(:workflow_executions)

    drop constraint(:workflow_nodes, "workflow_nodes_workflow_id_fkey")

    drop table(:workflow_nodes)
  end
end
