defmodule Fitzyo.Repo.Migrations.AddCartLineSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cart_items) do
      add :source, :text, null: false, default: "human"
    end
  end

  def down do
    alter table(:cart_items) do
      remove :source
    end
  end
end
