defmodule Fitzyo.Repo.Migrations.AddCartItemProposedVariant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cart_items) do
      add :proposed_variant_id, :text
    end
  end

  def down do
    alter table(:cart_items) do
      remove :proposed_variant_id
    end
  end
end
