defmodule Fitzyo.Repo.Migrations.CreateCarts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cart_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :bigint, null: false, default: 1
      add :label, :text
      add :unit_price, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :cart_id, :uuid, null: false

      add :variant_id,
          references(:variants,
            column: :id,
            name: "cart_items_variant_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:cart_items, [:cart_id, :variant_id],
             name: "cart_items_unique_variant_per_cart_index"
           )

    create table(:carts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:cart_items) do
      modify :cart_id,
             references(:carts,
               column: :id,
               name: "cart_items_cart_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:carts) do
      add :last_order_number, :text
      add :checked_out_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:carts) do
      remove :updated_at
      remove :inserted_at
      remove :checked_out_at
      remove :last_order_number
    end

    drop constraint(:cart_items, "cart_items_variant_id_fkey")

    drop constraint(:cart_items, "cart_items_cart_id_fkey")

    alter table(:cart_items) do
      modify :cart_id, :uuid
    end

    drop table(:carts)

    drop_if_exists unique_index(:cart_items, [:cart_id, :variant_id],
                     name: "cart_items_unique_variant_per_cart_index"
                   )

    drop table(:cart_items)
  end
end
