defmodule Fitzyo.Repo.Migrations.Slice2GraphPersistence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflows) do
      add :nodes, {:array, :map}, default: []
      add :edges, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:workflows) do
      remove :edges
      remove :nodes
    end
  end
end
