defmodule Fitzyo.Repo.Migrations.CreateCatalog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:categories, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :position, :bigint, null: false, default: 0
    end

    create table(:products, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :name, :text, null: false
      add :brand, :text, null: false
      add :description, :text
      add :price, :decimal, null: false
      add :currency, :text, null: false, default: "USD"
      add :gender, :text, null: false, default: "unisex"
      add :age_group, :text, null: false, default: "adult"
      add :material, :text
      add :fit, :text, null: false, default: "regular"
      add :stretch, :text, null: false, default: "low"
      add :fit_length, :text, default: "regular"
      add :cut, :text
      add :weight, :text
      add :activities, {:array, :text}, null: false, default: []
      add :image_url, :text
      add :size_system, :text, null: false, default: "US"
      add :measurement_unit, :text, null: false, default: "inches"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id,
          references(:categories,
            column: :id,
            name: "products_category_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:products, [:brand])

    create index(:products, [:fit])

    create index(:products, [:price])

    create index(:products, [:activities], using: "GIN")

    create table(:size_guide_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :size, :text, null: false
      add :position, :bigint, null: false, default: 0
      add :chest_min, :decimal
      add :chest_max, :decimal
      add :waist_min, :decimal
      add :waist_max, :decimal
      add :hip_min, :decimal
      add :hip_max, :decimal
      add :neck, :decimal
      add :sleeve, :decimal
      add :inseam, :decimal

      add :product_id,
          references(:products,
            column: :id,
            name: "size_guide_entries_product_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:size_guide_entries, [:product_id, :size],
             name: "size_guide_entries_unique_size_per_product_index"
           )

    create table(:variants, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :size, :text, null: false
      add :color, :text, null: false
      add :color_hex, :text
      add :sku, :text
      add :price, :decimal, null: false
      add :inventory_quantity, :bigint, null: false, default: 0
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id,
          references(:products,
            column: :id,
            name: "variants_product_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:variants, [:product_id, :position])

    create index(:variants, [:size])

    create index(:variants, [:color])
  end

  def down do
    drop_if_exists index(:variants, [:color])

    drop_if_exists index(:variants, [:size])

    drop_if_exists index(:variants, [:product_id, :position])

    drop constraint(:variants, "variants_product_id_fkey")

    drop table(:variants)

    drop constraint(:size_guide_entries, "size_guide_entries_product_id_fkey")

    drop_if_exists unique_index(:size_guide_entries, [:product_id, :size],
                     name: "size_guide_entries_unique_size_per_product_index"
                   )

    drop table(:size_guide_entries)

    drop_if_exists index(:products, [:activities])

    drop_if_exists index(:products, [:price])

    drop_if_exists index(:products, [:fit])

    drop_if_exists index(:products, [:brand])

    drop constraint(:products, "products_category_id_fkey")

    drop table(:products)

    drop table(:categories)
  end
end
